# .streamlit/config.toml
# .streamlit/config.toml (Definitive)

[theme]
primaryColor = "#0d6efd"
backgroundColor = "#d0e0f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#31333F"
font = "sans serif"
